try {
    console.lg('SUCCESS!');
} catch (e) {
    console.log('ERROR =>', e);
}